### PR TITLE
use new AbstractMongoCRUDTestController

### PR DESCRIPTION
**Pull request by dcrissman**
Depends on https://github.com/lightblue-platform/lightblue-mongo/pull/92

### CODE REVIEW

**Comment by dcrissman** [comment]
Also depends on https://github.com/lightblue-platform/lightblue-rest/issues/123

**Comment by luan-cestari** [comment]
Hi @dcrissman , is there any PR pending for this ? I saw https://github.com/lightblue-platform/lightblue-rest/issues/123 but it seems there is no PR for it and the build of this PR is broken (I'm restarting Travis build process to see if it works now)

**Comment by dcrissman** [comment]
The PR is https://github.com/lightblue-platform/lightblue-rest/pull/124

**Comment by luan-cestari** [comment]
Merged. I will wait for the travis now

**Comment by dcrissman** [comment]
Ready for review

**Pull request merged**
