### PR TITLE
make methods public instead of protected

### PR DESCRIPTION
**Pull request by dcrissman**

### CODE REVIEW

**Comment by paterczm** [comment]
Didn't you want to remove this project and distribute it's code among 2 others?

**Comment by dcrissman** [comment]
I do, and that is still over in #19.

**Comment by dcrissman** [comment]
This failed because of a failed master branch build.

**Comment by paterczm** [comment]
> I do, and that is still over in #19.

Is it not better to merge refactored code before making any changes?

**Comment by dcrissman** [comment]
> > I do, and that is still over in #19.
> 
> Is it not better to merge refactored code before making any changes?

Agreed, just waiting on someone to merge #19. In which case this PR becomes invalid, because the functionality is moved to lightblue-client.

**Comment by dcrissman** [comment]
Moved to lightblue-client. Closing.

**Pull request closed without merging**
