### PR TITLE
Move client functionality

### PR DESCRIPTION
**Pull request by dcrissman**
Moving test functionality from lightblue-test-utils here.

This PR must be merged at the same time as https://github.com/lightblue-platform/lightblue-client/pull/100 because this reversed the dependency between the two modules.

This is related to https://github.com/lightblue-platform/lightblue-test-utils/issues/9

### CODE REVIEW

**Comment by dcrissman** [comment]
@paterczm What do you think about this PR?

**Comment by paterczm** [comment]
Let me know if I understand this correctly: You want to split lightblue-test into 2 modules, which will go to lightblue-rest and lightblue-client. Lightblue-rest will receive AbstractCRUDControllerWithRest base (no lightblue-client deps). Lightblue-test will receive AbstractCRUDControllerWithLBClient and test-example module.

What is the value? Less parent modules? An in memory lightblue instance for unit testing which does not include lightblue-client?

**Comment by dcrissman** [comment]
Dropping to an in-progress state until after Ana .5

**Comment by dcrissman** [comment]
@paterczm Kind of exactly what you said, but I think of it this way:
1. One less dependency/project to maintain
2. This change will allow us to perform integration testing around the lightblue-client itself without creating a circular dependency between projects.
3. (and to a lesser degree) If we ever create an alternative to the lightblue-client, we could reuse AbstractCRUDControllerWithRest.

**Comment by paterczm** [comment]
We wouldn't have circular dependency problems if tests are in a separate project. I only see points 1 and 3 as benefits. I'm not sure it's worth it, but since you already did it, I don't see why not merge it. This change has to be communicated to AMS, I think they're using AbstractCRUDControllerWithRest already.

**Comment by dcrissman** [comment]
To me the second point is my main one, so if this doesn't make sense then lets not do it. We could create a separate project for lightblue-client integration testing, but I would prefer not to go this route but rather keep everything in the same project.

Similar to what I did for <a href="https://github.com/lightblue-platform/lightblue-ldap/tree/master/lightblue-ldap-integration-test">lightblue-ldap</a>, I want to create a integration module for the lightblue-client project and write tests that guarantee it does what it is suppose to.

**Comment by dcrissman** [comment]
Artifacts for Ana 1.5 have been cut and is more of less out the door. Moving back into a ready for review status.

**Comment by dcrissman** [comment]
Marking with as an open question so we can discuss this change as a team.

**Comment by luan-cestari** [comment]
I saw both https://github.com/lightblue-platform/lightblue-client/pull/100 and https://github.com/lightblue-platform/lightblue-test-utils/pull/19 . I strong agree about what @dcrissman mention in https://github.com/lightblue-platform/lightblue-test-utils/pull/19#issuecomment-97090999 . Let me know if someone else disagree, otherwise I will merge both PRs

**Pull request merged**
